# Generated by Django 3.0 on 2020-07-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tshirtapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='Username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='Email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
