# Generated by Django 3.0.6 on 2020-08-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[    
    ]
   

    operations = [
        migrations.CreateModel(
            name='Men',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Brand', models.CharField(max_length=100)),
                ('Size', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='pics')),
            ],
        ),
        
    ]
