# Generated by Django 3.0 on 2020-08-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tshirtapp', '0003_auto_20200808_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Women',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W_Name', models.CharField(max_length=100)),
                ('W_Brand', models.CharField(max_length=100)),
                ('W_Size', models.CharField(max_length=100)),
                ('W_Price', models.CharField(max_length=100)),
                ('W_Image', models.ImageField(upload_to='w_pics')),
            ],
        ),
    ]
