# Generated by Django 3.0 on 2020-10-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tshirtapp', '0004_women'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Brand', models.CharField(max_length=100)),
                ('Size', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='pics')),
                ('Gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Men',
        ),
        migrations.DeleteModel(
            name='Women',
        ),
    ]
