# Generated by Django 3.0.6 on 2020-10-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tshirtapp', '0007_auto_20201004_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.FloatField(),
        ),
    ]
